import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties
import java.io.FileInputStream

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.composeHotReload)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.sqldelight)
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true

            binaryOption("bundleId", "com.cinescope.cinescope.ComposeApp")

            linkerOpts.add("-lsqlite3")
            export(libs.sqldelight.runtime)
            export(libs.sqldelight.native.driver)

            export(compose.components.resources)
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.sqldelight.android.driver)
            implementation(libs.ktor.client.cio)
        }

        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            api(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.client.logging)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.sqldelight.runtime)
            implementation(libs.sqldelight.coroutines)
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.voyager.navigator)
            implementation(libs.voyager.tab.navigator)
            implementation(libs.voyager.transitions)
            implementation(libs.voyager.koin)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor)
            implementation(libs.kotlinx.datetime)
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)

            api(libs.sqldelight.native.driver)
        }
    }
}

android {
    namespace = "com.cinescope.cinescope"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.cinescope.cinescope"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    debugImplementation(compose.uiTooling)
}

sqldelight {
    databases {
        create("CineScopeDatabase") {
            packageName.set("com.cinescope.cinescope.data.local.database")
        }
    }
}

abstract class GenerateBuildConfigTask : DefaultTask() {
    @get:Input
    @get:Optional
    abstract val apiKey: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val tmdbApiKey = apiKey.orNull ?: throw GradleException(
            """
            TMDB API key not found!

            Please add your API key to local.properties:
                tmdb.api.key=your_api_key_here

            OR set the environment variable:
                export TMDB_API_KEY=your_api_key_here

            Get your free API key at: https://www.themoviedb.org/settings/api
            """.trimIndent()
        )

        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText("""
            |package com.cinescope.cinescope
            |
            |/**
            | * Auto-generated BuildConfig file
            | * DO NOT EDIT MANUALLY - This file is generated by the generateBuildConfig Gradle task
            | *
            | * To update, modify local.properties or set TMDB_API_KEY environment variable
            | */
            |object BuildConfig {
            |    const val TMDB_API_KEY = "$tmdbApiKey"
            |    const val TMDB_BASE_URL = "https://api.themoviedb.org/3"
            |    const val IMAGE_BASE_URL = "https://image.tmdb.org/t/p"
            |}
            |
        """.trimMargin())

        println("✅ BuildConfig.kt generated successfully!")
    }
}

tasks.register<GenerateBuildConfigTask>("generateBuildConfig") {
    val localPropertiesFile = rootProject.file("local.properties")
    val localProperties = Properties()

    val key = if (localPropertiesFile.exists()) {
        localProperties.load(FileInputStream(localPropertiesFile))
        localProperties.getProperty("tmdb.api.key")
    } else {
        null
    } ?: System.getenv("TMDB_API_KEY")

    if (key != null) {
        apiKey.set(key)
    }

    outputFile.set(project.file("src/commonMain/kotlin/com/cinescope/cinescope/BuildConfig.kt"))
}

tasks.matching { task ->
    task.name.startsWith("compileKotlin")
}.configureEach {
    dependsOn("generateBuildConfig")
}
