package com.cinescope.cinescope.domain.model

/**
 * Represents a personalized movie recommendation with scoring and explanation.
 *
 * This data class encapsulates a recommended movie along with a match score indicating
 * how well the recommendation aligns with the user's preferences, and a human-readable
 * explanation for why this movie was recommended.
 *
 * The match score is generated by the recommendation engine using a hybrid algorithm
 * that combines content-based filtering (analyzing genre preferences from user ratings)
 * with popularity metrics from TMDB.
 *
 * @property movie The recommended movie instance
 * @property matchScore Confidence score from 0.0 (weak match) to 1.0 (perfect match)
 * @property reason Human-readable explanation of why this movie was recommended
 *
 * @throws IllegalArgumentException if matchScore is not between 0.0 and 1.0
 *
 * @see com.cinescope.cinescope.domain.recommendation.RecommendationEngine
 * @see Movie
 */
data class Recommendation(
    val movie: Movie,
    val matchScore: Double,
    val reason: String
) {
    init {
        require(matchScore in 0.0..1.0) { "Match score must be between 0.0 and 1.0" }
    }
}
